version: '3.4'

services:
  keeptrack:
    image: keeptrack
    build:
      context: keeptrack
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
    volumes:
      - /app/node_modules
      - ./keeptrack:/app
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
